##################################
#@author erik.flores 
#@fecha 26/JUNIO/2017
##################################
#modificacion 20/11/2017
#motivo: se crea usuario personalizado para monitoreo de eventos PLAVIT
##################################
#modificacion 18/12/2017
#motivo: Se modifica query de consulta de fecha ultimo evento.
##################################
#modificacion 27/08/2021
#motivo: Se agrega tabla de eventos Parqueo Positivo
##################################
#RUTA-UBICACION DEL ARCHIVO DE CONFIGURACION DEL log4j2
LOG4J2.SUBDIRECTORY=/resources/log4j2.xml

#PARAMETROS DE BASE DE DATOS
DB.DRIVER=com.mysql.jdbc.Driver
DB.SERVER=srv00pcr03.atm.local
DB.PORT=3306
#URL SOLO SE DECLARA LO INHERENTE AL RDBMS
DB.URL=jdbc:mysql://srv00pcr03.atm.local:3306/CAMERAS
#DB.URL=jdbc:oracle:thin
#DB.URL=
DB.DATABASE=fotoradar_atm
DB.USER=BWUOxqSMtyynRpu7ZwOKqA\=\=
DB.PASSWD=O8z7f/wN/Bm2iAt6TpQ4LA\=\=

#############################################################################################
#INTERVALO DE TIEMPO EN DIAS PARA VERIFICACION DE EVENTOS 
SQL.INTERVALO=90

#############################################################################################
#TABLAS A DEPURAR
LIST.TABLAS=MESSAGES|EVENTS|VALIDACION_ATM|INTAURORA
LIST.QUERYS=Q1|Q2|Q3

#############################################################################################
#TABLAS A DEPURAR
MESSAGES.Q1=select count(1) cantidad from cameras.messages as a where a.time < DATE_SUB(date_format(now(),'%Y-%m-%d'), INTERVAL ? DAY)
MESSAGES.Q2=INSERT INTO HISTORICA.MESSAGES_HIST select * from cameras.messages as a where time < DATE_SUB(date_format(now(),'%Y-%m-%d'), INTERVAL ? DAY) and a.id not in ( select b.id from historica.messages_hist as b where a.id = b.id)
MESSAGES.Q3=delete from cameras.messages where time < DATE_SUB(date_format(now(),'%Y-%m-%d'), INTERVAL ? DAY)

EVENTS.Q1=select count(1) as cantidad from cameras.events as a where a.ping_date < DATE_SUB(date_format(now(),'%Y-%m-%d'), INTERVAL ? DAY)
EVENTS.Q2=insert into historica.events_hist select * from cameras.events as a where a.ping_date < DATE_SUB(date_format(now(),'%Y-%m-%d'), INTERVAL ? DAY) and a.id not in ( select b.id from historica.events_hist as b where a.id = b.id)
EVENTS.Q3=delete from cameras.events where ping_date < DATE_SUB(date_format(now(),'%Y-%m-%d'), INTERVAL ? DAY)

VALIDACION_ATM.Q1=select count(1) as cantidad from fotoradar_atm.validacion_atm as a where  a.fecha_captura < DATE_SUB(date_format(now(),'%Y-%m-%d'), INTERVAL ? DAY)
VALIDACION_ATM.Q2=insert into historica.validacion_atm_hist select * from fotoradar_atm.validacion_atm as a where a.fecha_captura < DATE_SUB(date_format(now(),'%Y-%m-%d'), INTERVAL ? DAY) and a.id_validacion not in ( select b.id_validacion from historica.validacion_atm_hist as b where a.id_validacion = b.id_validacion )
VALIDACION_ATM.Q3=delete from fotoradar_atm.validacion_atm where fecha_captura < DATE_SUB(date_format(now(),'%Y-%m-%d'), INTERVAL ? DAY)

INTAURORA.Q1=select count(1) as cantidad from fotoradar_atm.intaurora as a where a.fecha_incidente < DATE_SUB(date_format(now(),'%Y-%m-%d'), INTERVAL ? DAY)
INTAURORA.Q2=insert into historica.intaurora_hist select * from fotoradar_atm.intaurora as a where a.fecha_incidente < DATE_SUB(date_format(now(),'%Y-%m-%d'), INTERVAL ? DAY) and a.idintaurora not in ( select b.idintaurora from historica.intaurora_hist as b where a.idintaurora = b.idintaurora )
INTAURORA.Q3=delete from fotoradar_atm.intaurora where fecha_incidente < DATE_SUB(date_format(now(),'%Y-%m-%d'), INTERVAL ? DAY)

#############################################################################################
#SENTENCIA A EJECUTAR
INFORMATION_SCHEMA.Q1=SELECT 'Datos (GB)' AS tipo, SUM(ROUND(data_length / 1024 / 1024 / 1024, 2)) AS tamanio FROM information_schema.TABLES UNION ALL SELECT '\u00cdndices (GB)' AS tipo, SUM(ROUND(index_length / 1024 / 1024 / 1024, 2)) AS tamanio FROM information_schema.TABLES
#INFORMATION_SCHEMA.Q11=SELECT table_schema AS basedato, sum(round(((data_length + index_length) / 1024 / 1024 / 1024), 2)) as tamanio FROM information_schema.TABLES group by table_schema
INFORMATION_SCHEMA.Q2=
INFORMATION_SCHEMA.Q3=

#############################################################################################
#PARAMETROS NOTIFICACION POR CORREO
MAIL.SERVER=act.atm.gob.ec
MAIL.PASS=rOWHl5GhdqnUc/0NgqmpqQ\=\=
MAIL.FROM=WjeO5u7JEr8jUFGu2gdFvcfJH/sChU4d4kWGZiKzNyxSBDqEzIq+vI8VwA8Xqeoi
MAIL.TO=erik.flores@atm.gob.ec;
MAIL.CC=
#MAIL.CC=washington.pino@atm.gob.ec;alertas.informatica@atm.gob.ec;notificaciones@atm.gob.ec;
MAIL.BCC=
MAIL.SUBJECT=TEST Movimiento de historico de tabla 
MAIL.BODY=TEST Informe del proceso de movimiento de datos historicos de la tabla 
MAIL.PORT=587

#############################################################################################



